from fedora:latest

# Update all packages
RUN dnf update -y

# R is a dependency to this package and must be installed
# prior to installing the R-python pacakge.
RUN dnf install -y \
    R \
    python3-devel \
    python3-pip \
    git \
    openssh \
    openssh-clients \
    emacs \
    vim \
    gcc \
    gcc-c++

# Copy All ssh keys over from the home environment. This
# will allow us to grab the github project
# Note: You will need to copy your ssh private key here as `id_rsa`
COPY id_rsa /root/.ssh/id_rsa
RUN chmod -R 600 /root/.ssh

RUN ssh-keyscan -t rsa github.com >> /root/.ssh/known_hosts

# Grab the lastest package source.
RUN git clone git@github.com:{{ USER }}/predictor.git


# Grab my specific source code for the FEAST project
# I forked this project (do NOT own it) and have made my modifications 
# so that there is an extensive python extension. 
# Pull that data here and build the source on this vm
RUN git clone git@github.com:barbacbd/FEAST.git
RUN cd FEAST && git checkout pyfeast_v2 
RUN cd FEAST/python && bash -c "./build.sh"

# upgrade pip
RUN python3 -m pip install pip --upgrade

# install the project requirements
RUN python3 -m pip install -r predictor/requirements.txt

RUN git config --global user.email "{{ EMAIL }}"
RUN git config --global user.name "{{ FULLNAME }}"